import { Button, ButtonLink } from './ui/button';
import { file, useIcons } from '../site';
import { LibraryLink, Symbol } from './Ui';

export function IconLibrary() {
  const s=useIcons(),{t,catalog,filters,results,dark}=s;
  const all=filters.collection==='all',collection=catalog.collections.find(c=>c.id===filters.collection),category=catalog.categories.find(c=>c.id===filters.category);
  const filter=(values:Partial<typeof filters>)=>s.setFilters(current=>({...current,...values,limit:72}));
  return <section className="workspace" id="library" aria-label={t.navLibrary}>
    <aside className="sidebar"><div className="sidebar-top"><span className="eyebrow">{t.library}</span><span className="tiny-pill">{catalog.icons.length}</span></div>
      <section className="sidebar-group" aria-labelledby="collection-heading"><h2 className="category-heading" id="collection-heading">{t.collectionLabel}</h2><div className="collection-list"><Button variant="ghost" size="sm" className="category-button h-auto w-auto justify-between whitespace-nowrap text-left min-[761px]:w-full min-[761px]:whitespace-normal" data-collection="all" aria-pressed={all} onClick={()=>s.selectCollection('all')}><span>{t.allCollections}</span><small>{catalog.icons.length}</small></Button>{[...catalog.collections].sort((a,b)=>Number(b.id==='alibaba-cloud')-Number(a.id==='alibaba-cloud')).map(c=><Button variant="ghost" size="sm" key={c.id} className="category-button h-auto w-auto justify-between whitespace-nowrap text-left min-[761px]:w-full min-[761px]:whitespace-normal" data-collection={c.id} aria-pressed={filters.collection===c.id} onClick={()=>s.selectCollection(c.id)}><span>{s.title(c)}</span><small>{c.count}</small></Button>)}</div></section>
      <section className="sidebar-group category-group" aria-labelledby="category-heading"><h2 className="category-heading" id="category-heading">{t.categoryLabel}<span>{all?t.allCollections:s.title(collection!)}</span></h2><div className="category-list"><Button variant="ghost" size="sm" className="category-button h-auto w-auto justify-between whitespace-nowrap text-left min-[761px]:w-full min-[761px]:whitespace-normal" data-category="all" aria-pressed={filters.category==='all'} onClick={()=>filter({category:'all'})}><span><Symbol name="grid"/>{t.all}</span><small>{all?catalog.icons.length:collection!.count}</small></Button>{s.visibleCategories.map(c=><Button variant="ghost" size="sm" key={c.id} className="category-button h-auto w-auto justify-between whitespace-nowrap text-left min-[761px]:w-full min-[761px]:whitespace-normal" data-category={c.id} aria-pressed={filters.category===c.id} onClick={()=>filter({category:c.id})}><span>{s.title(c)}</span><small>{c.count}</small></Button>)}</div></section><LibraryLink className="open-all-sidebar h-auto min-h-9 whitespace-normal"/>
    </aside>
    <div className="library-main"><div className="library-toolbar"><div className="filter-row" aria-label={t.softwareType}>{['all','open-source','source-available','commercial','unverified'].map(type=><Button variant="secondary" size="sm" key={type} className="filter-chip text-xs aria-pressed:bg-accent aria-pressed:text-foreground" data-type={type} aria-pressed={type===filters.type} onClick={()=>filter({type})}>{type==='all'?t.allTypes:s.typeLabel(type)}</Button>)}</div><div className="background-toggle" role="group" aria-label={t.preview}><Button variant="ghost" size="icon-sm" id="light" aria-label={t.light} title={t.light} aria-pressed={!dark} onClick={()=>s.setDark(false)}><span className="light-dot"/></Button><Button variant="ghost" size="icon-sm" id="dark" aria-label={t.dark} title={t.dark} aria-pressed={dark} onClick={()=>s.setDark(true)}><span className="dark-dot"/></Button></div></div>
      <div id="query-filter" className="query-filter" hidden={!filters.query}>{filters.query&&<><span>{t.searchLabel}: <strong>{filters.query}</strong></span><Button variant="ghost" size="sm"  id="clear-query" onClick={()=>{filter({query:''});s.setFocusRequest({kind:'heading'});}}>{t.clear}<Symbol name="close"/></Button></>}</div>
      <div className="section-heading"><div><h2 id="category-title" tabIndex={-1}>{category?s.title(category):all?t.allIcons:s.title(collection!)}</h2><p id="category-description">{category?(s.locale==='en'?category.descriptionEn:category.description):t.allDescription}</p></div><span id="result-count" className="result-count" role="status" aria-live="polite">{results.length} {t.results}</span></div>
      <div id="category-actions" className="category-actions">{category?<><Button variant="default" size="sm"  id="open-category" onClick={()=>s.openLibraries([category])}>{t.openDrawio}<Symbol name="external"/></Button><ButtonLink variant="ghost" size="sm"  href={file(category.libraries[s.locale])} download><Symbol name="download"/>{t.downloadLibrary}</ButtonLink></>:<><LibraryLink size="sm"/><ButtonLink variant="ghost" size="sm"  href={file(all?'libraries/combined.xml':collection!.allLibrary)} download><Symbol name="download"/>{t.allLibrary}</ButtonLink></>}</div>
      <div className={`icon-grid${dark?' dark-preview':''}`} id="grid">{results.length?results.slice(0,filters.limit).map(icon=><Button variant="outline" size="layout" key={icon.id} className={`icon-card${s.located===icon.id?' icon-located ring-4 ring-ring/30':''}`+" block min-w-0 whitespace-normal text-left"} data-icon={icon.id} aria-label={`${s.iconName(icon)} — ${t.details}`} onClick={()=>s.setModal({kind:'detail',icon})}><span className="icon-stage"><img src={file(icon.asset)} alt="" loading="lazy" width="48" height="48"/><span className="card-arrow"><Symbol name="arrow"/></span></span><span className="card-info"><strong>{s.iconName(icon)}</strong><small>{s.title(catalog.categories.find(c=>c.id===icon.category)!)}</small></span><span className={`type-dot type-${icon.softwareType}`} title={s.typeLabel(icon.softwareType)} aria-label={s.typeLabel(icon.softwareType)}/></Button>):<div className="empty"><Symbol name="search"/><h3>{t.emptyTitle}</h3><p>{t.emptyText}</p><Button variant="outline" size="default" id="clear"  onClick={()=>{s.selectCollection('all',true);s.setFocusRequest({kind:'heading'});}}>{t.clear}</Button></div>}</div>
      <div id="more" className="more">{results.length>filters.limit&&<><span>{t.showing} {filters.limit}{t.of}{results.length}</span><Button variant="outline" size="default"  id="load-more" onClick={()=>s.setFilters(current=>({...current,limit:current.limit+72}))}>{t.loadMore}<Symbol name="arrow"/></Button></>}</div>
    </div>
  </section>;
}
