import {readFile} from 'node:fs/promises';
import {selection} from '../data/selection.mjs';
import {json,hash,inspectSvg} from './lib.mjs';
const catalog = await json('data/catalog.json');
const categories = await json('data/categories.json');
const sources = await json('data/sources.lock.json');
const fail = message => {throw Error(message);};
if(catalog.schemaVersion !== 1 || catalog.icons.length < 300) fail('Catalog must contain at least 300 icons');
const ids = new Set(), categoryIds = new Set(categories.map(c=>c.id));
const selected = new Map(selection.map(i=>[i.id,i]));
if(catalog.icons.length !== selection.length) fail('Catalog is out of sync with selection');
for(const icon of catalog.icons) {
  if(!/^[a-z0-9-]+$/.test(icon.id) || ids.has(icon.id)) fail(`Invalid or duplicate ID: ${icon.id}`);
  ids.add(icon.id);
  const seed = selected.get(icon.id);
  if(!seed || Object.entries(seed).some(([key,value])=>key !== 'source' && JSON.stringify(icon[key]) !== JSON.stringify(value))) fail(`Stale metadata: ${icon.id}`);
  if(!categoryIds.has(icon.category)) fail(`Unknown category: ${icon.id}`);
  if(!['open-source','source-available','commercial','unverified'].includes(icon.softwareType)) fail(`Invalid type: ${icon.id}`);
  if(icon.softwareType==='commercial' && (icon.usagePolicy!=='drawio-architecture-only' || icon.usagePolicyUrl!=='ICON_USAGE.md' || icon.brandPermissionStatus!=='not-verified')) fail(`Missing commercial usage policy: ${icon.id}`);
  if(!icon.name || !Array.isArray(icon.aliases) || !icon.tags.length) fail(`Incomplete metadata: ${icon.id}`);
  if(new URL(icon.homepage).protocol !== 'https:') fail(`Invalid project URL: ${icon.id}`);
  const source=sources[icon.source.id];
  if(!source || icon.source.revision !== source.revision || !/^[a-f0-9]{40}$/.test(source.revision)) fail(`Invalid source pin: ${icon.id}`);
  if(!icon.source.url.includes(`/${source.revision}/`) || !icon.source.licenseUrl || !icon.source.collectionLicense || !/^[a-f0-9]{64}$/.test(icon.source.sha256)) fail(`Incomplete provenance: ${icon.id}`);
  if(icon.asset !== `icons/${icon.id}.svg`) fail(`Invalid asset path: ${icon.id}`);
  const svg=await readFile(`assets/${icon.asset}`,'utf8');
  if(hash(svg)!==icon.sha256) fail(`Checksum mismatch: ${icon.id}`);
  const size=inspectSvg(svg);
  if(size.width!==icon.width || size.height!==icon.height) fail(`Dimension mismatch: ${icon.id}`);
}
for(const c of categories) if(!catalog.icons.some(i=>i.category===c.id)) fail(`Empty category: ${c.id}`);
for(const id of Object.keys(sources)) if((await readFile(`licenses/${id}-LICENSE.txt`,'utf8')).length<100) fail(`Missing license: ${id}`);
console.log(`Validated ${ids.size} unique icons, ${categories.length} categories, SVG safety, hashes and provenance.`);
